name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build and deploy to GitHub Pages
        run: |
          npm run build
          git config --global user.email "guillemin.matt@gmail.com"
          git config --global user.name "MattGuil"
          git checkout --orphan gh-pages
          git --work-tree dist add --all
          git --work-tree dist commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force