name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # document:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build and deploy to GitHub Pages
        run: |
          npm run build
          git config --global user.email "guillemin.matt@gmail.com"
          git config --global user.name "MattGuil"
          git checkout --orphan gh-pages
          git --work-tree dist add --all
          git --work-tree dist commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f main
          git branch -D gh-pages